services:
  - type: web
    name: telegram-vc-music-bot
    plan: free
    runtime: docker
    autoDeploy: true
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
